version: "2.4"
services:
  api:
    build: ./api
    volumes:
      - ./api:/var/task
    working_dir: /var/task
    environment:
      - HOME=/tmp
    entrypoint: ["poetry", "run"]
    user: "${COMPOSE_UID:-1000}:${COMPOSE_GID:-1000}"
    command: ["uvicorn", "main:app", "--reload", "--host=0.0.0.0"]
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=manifoods
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - db
volumes:
  postgres_data: